/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
export default {
  knowledgeSidebar: [
    'index',
    {type: 'link', label: '基础知识', href: '/bases/'},
    {type: 'link', label: '百科', href: '/wiki/'},
    {type: 'link', label: '自部署', href: '/self-hosted/'},
    {type: 'link', label: '工具对比与实践', href: '/compare/'},
    {type: 'link', label: '解决方案', href: '/solution/'},
    {type: 'link', label: '问题与解答', href: '/issue/'},
  ],
  basesSidebar: [
    'bases/index',
    {type: 'link', label: '数据结构', href: '/bases/data-structures/'},
    {type: 'link', label: '计算机网络', href: '/bases/computer-network/'},
    {type: 'link', label: '计算机组成原理', href: '/bases/computer-organization/'},
    {type: 'link', label: '操作系统', href: '/bases/operating-system/'},
  ],
  dataStructuresSidebar: [{type: 'autogenerated', dirName: 'bases/data-structures'}],
  computerNetworkSidebar: [{type: 'autogenerated', dirName: 'bases/computer-network'}],
  computerOrganizationSidebar: [{type: 'autogenerated', dirName: 'bases/computer-organization'}],
  operatingSystemSidebar: [{type: 'autogenerated', dirName: 'bases/operating-system'}],
  wikiSidebar: [{type: 'autogenerated', dirName: 'wiki'}],
  selfHostedSidebar: [{type: 'autogenerated', dirName: 'self-hosted'}],
  articlesSidebar: [
    'articles',
    {type: 'category', label: '工具对比与实践', items: [{type: 'autogenerated', dirName: 'compare'}]},
    {type: 'category', label: '解决方案', items: [{type: 'autogenerated', dirName: 'solution'}]},
    {type: 'category', label: '问题与解答', items: [{type: 'autogenerated', dirName: 'issue'}]},
  ],
};
