/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
export default {
  basesSidebar: [{type: 'autogenerated', dirName: 'bases'}],
  wikiSidebar: [{type: 'autogenerated', dirName: 'wiki'}],
  articlesSidebar: [
    'articles',
    {type: 'category', label: '工具对比与实践', items: [{type: 'autogenerated', dirName: 'compare'}]},
    {type: 'category', label: '解决方案', items: [{type: 'autogenerated', dirName: 'solution'}]},
    {type: 'category', label: '问题与解答', items: [{type: 'autogenerated', dirName: 'issue'}]},
  ],
};
